image: fedora:latest

stages:
  - tar
  - build
  - package

build-tar:
  stage: tar
  script:
    - dnf -y install git autoconf automake libtool libxslt docbook-style-xsl bison flex make
    - ./autogen.sh
    - ./configure
    - make dist-gzip
  artifacts:
    expire_in: 1 week
    paths:
      - "*.tar.gz"

.build:dev: &build_deb
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - apt-get update
    - apt-get upgrade -y
    - apt-get install -y build-essential devscripts equivs
    - tar xzf *.tar.gz
    - cd monitoringplug*/
    - yes | mk-build-deps --install --install debian/control
    - ./configure
    - make

.build:fc: &build_fc
  stage: build
  variables:
    GIT_STRATEGY: none
  script:
    - dnf -y upgrade
    - dnf -y install @buildsys-build dnf-plugins-core
    - tar xzf *.tar.gz
    - cd monitoringplug*/
    - dnf -y builddep --spec  contrib/monitoringplug.spec
    - ./configure
    - make

build:bionic:
  image: ubuntu:bionic
  <<: *build_deb

build:xenial:
  image: ubuntu:xenial
  <<: *build_deb

build:fc28:
  image: fedora:28
  <<: *build_fc

.package:fc: &package_fc
  stage: package
  variables:
    GIT_STRATEGY: none
  script:
    - dnf -y upgrade
    - dnf -y install @buildsys-build dnf-plugins-core
    - tar --strip-components=1 -xzf monitoringplug-*.tar.gz monitoringplug-*/contrib/monitoringplug.spec
    - dnf -y builddep --spec  contrib/monitoringplug.spec
    - rpmbuild -ba --define="_sourcedir ${CI_PROJECT_DIR}" --define="_topdir ${CI_PROJECT_DIR}" contrib/monitoringplug.spec
  artifacts:
    expire_in: 1 week
    paths:
      - "RPMS/*/*.rpm"
      - "SRPMS/*.rpm"

package:fc28:
  image: fedora:28
  <<: *package_fc
